### ISSUE TITLE
Fix renderization on mobile and smaller viewports

### ISSUE THREAD

**Issue by jtemporal** [jtemporal/gitfichas#166]
On mobile the cards are hanging left and not easy to read as seen in the image below.

![IMG_0402](https://github.com/user-attachments/assets/52959059-37f2-4955-b260-ebd3e7fe85af)

**Comment by PedroCZuffo** [comment]
@jtemporal posso pegar essa issue?

**Comment by jtemporal** [comment]
> @jtemporal posso pegar essa issue?

Pedro pode mandar o PR até onde eu sei não ninguém trabalhando nisso ainda.

**Comment by GomesMarcos** [comment]
Eu tenho um palpite do que pode ser, mas não vi no Readme como rodar localmente 😅😅
Vou criar uma branch e te envio, @PedroCZuffo

**Comment by jtemporal** [comment]
> Eu tenho um palpite do que pode ser, mas não vi no Readme como rodar localmente 😅😅


Instruções de como rodar estão no [CONTRIBUTING.md](/jtemporal/gitfichas/blob/main/CONTRIBUTING.md). ☺️

**Comment by GomesMarcos** [comment]
Vi lá! Muito obrigado! <3
Como faço pra criar uma branch? tentei e estou recebendo um "You Shall Not Pass" hehuehuehue

**Comment by jtemporal** [comment]
> Como faço pra criar uma branch? tentei e estou recebendo um "You Shall Not Pass" hehuehuehue

Acho que vc precisa fazer um fork primeiro e aí criar a branch no seu fork 🤔
